"""fix publish_at

Revision ID: 373dd632b539
Revises: db7489e2c172
Create Date: 2025-11-06 13:19:19.419645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '373dd632b539'
down_revision: Union[str, Sequence[str], None] = 'db7489e2c172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('youtube_channel', 'published_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_channel', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('video', 'published_at')
    # ### end Alembic commands ###
