"""add parse

Revision ID: 544de41adc3a
Revises: 0a0d638d13e8
Create Date: 2025-11-06 10:50:07.563589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544de41adc3a'
down_revision: Union[str, Sequence[str], None] = '0a0d638d13e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_channel',
    sa.Column('youtube_channel_id', sa.UUID(), nullable=False),
    sa.Column('etag', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_url', sa.String(length=100), nullable=True),
    sa.Column('platform_channel_id', sa.String(length=50), nullable=False),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('youtube_channel_id', name=op.f('pk_youtube_channel')),
    sa.UniqueConstraint('platform_channel_id', name=op.f('uq_youtube_channel_platform_channel_id'))
    )
    op.create_table('subscription',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('youtube_channel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['youtube_channel_id'], ['youtube_channel.youtube_channel_id'], name=op.f('fk_subscription_youtube_channel_id_youtube_channel'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', name=op.f('pk_subscription'))
    )
    op.create_table('video',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=20), nullable=False),
    sa.Column('count_views', sa.BigInteger(), nullable=True),
    sa.Column('count_likes', sa.Integer(), nullable=True),
    sa.Column('count_favorites', sa.Integer(), nullable=True),
    sa.Column('count_comments', sa.Integer(), nullable=True),
    sa.Column('youtube_channel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['youtube_channel_id'], ['youtube_channel.youtube_channel_id'], name=op.f('fk_video_youtube_channel_id_youtube_channel'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', name=op.f('pk_video')),
    sa.UniqueConstraint('youtube_video_id', name=op.f('uq_video_youtube_video_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('subscription')
    op.drop_table('youtube_channel')
    # ### end Alembic commands ###
